'use client';

import { useState, useEffect } from 'react';

interface VisionData {
    purpose: string;
    problem_statement: string;
}

interface VisionTabProps {
    projectId: string;
    initialData?: VisionData;
}

export default function VisionTab({ projectId, initialData }: VisionTabProps) {
    const [formData, setFormData] = useState<VisionData & { generated_output?: string }>({
        purpose: initialData?.purpose || '',
        problem_statement: initialData?.problem_statement || '',
        generated_output: (initialData as any)?.generated_output || ''
    });
    const [saving, setSaving] = useState(false);
    const [message, setMessage] = useState<{ type: 'success' | 'error', text: string } | null>(null);

    const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        setFormData(prev => ({
            ...prev,
            [e.target.name]: e.target.value
        }));
    };

    const handleSave = async () => {
        setSaving(true);
        setMessage(null);

        try {
            const res = await fetch(`/api/projects/${projectId}/vision`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(formData)
            });

            if (!res.ok) throw new Error('Failed to save vision');

            const result = await res.json();
            if (result.data) {
                setFormData(prev => ({
                    ...prev,
                    ...result.data
                }));
            }

            setMessage({ type: 'success', text: 'Vision saved & generated!' });

            // Clear message after 3s
            setTimeout(() => setMessage(null), 3000);

        } catch (error) {
            console.error(error);
            setMessage({ type: 'error', text: 'Failed to save changes' });
        } finally {
            setSaving(false);
        }
    };

    return (
        <div className="max-w-3xl mx-auto space-y-8 animate-in fade-in duration-500">
            <div className="space-y-2">
                <h2 className="text-2xl font-bold text-white">Project Vision</h2>
                <p className="text-neutral-400">Define the core purpose and problem you are solving. This context will guide all future AI generation.</p>
            </div>

            <div className="space-y-6">
                {/* Purpose Section */}
                <div className="space-y-2">
                    <label className="block text-sm font-medium text-neutral-300">Purpose</label>
                    <p className="text-xs text-neutral-500 mb-2">Why does this project exist? What is the high-level goal?</p>
                    <textarea
                        name="purpose"
                        value={formData.purpose}
                        onChange={handleChange}
                        rows={4}
                        className="w-full bg-neutral-900 border border-neutral-800 rounded-xl p-4 text-white placeholder-neutral-600 focus:outline-none focus:ring-2 focus:ring-blue-900/50 focus:border-blue-800 transition-all resize-none"
                        placeholder="e.g., To create a seamless platform for developers to document their APIs..."
                    />
                </div>

                {/* Problem Statement Section */}
                <div className="space-y-2">
                    <label className="block text-sm font-medium text-neutral-300">Problem Statement</label>
                    <p className="text-xs text-neutral-500 mb-2">What specific user pain points are you addressing? How are you solving them?</p>
                    <textarea
                        name="problem_statement"
                        value={formData.problem_statement}
                        onChange={handleChange}
                        rows={6}
                        className="w-full bg-neutral-900 border border-neutral-800 rounded-xl p-4 text-white placeholder-neutral-600 focus:outline-none focus:ring-2 focus:ring-blue-900/50 focus:border-blue-800 transition-all resize-none"
                        placeholder="e.g., Developers currently struggle with maintaining up-to-date documentation. Existing tools are..."
                    />
                </div>
            </div>

            {/* Generated Vision Display */}
            {(formData as any).generated_output && (
                <div className="space-y-2 pt-6 border-t border-neutral-800 animate-in fade-in slide-in-from-bottom-4 duration-700">
                    <div className="flex items-center justify-between">
                        <label className="block text-sm font-medium text-emerald-400">
                            ✨ Refined Vision (AI Generated)
                        </label>
                        <span className="text-xs text-neutral-500">Generated by Gemini</span>
                    </div>
                    <div className="bg-neutral-900/50 border border-neutral-800 rounded-xl p-6 prose prose-invert max-w-none text-sm leading-relaxed whitespace-pre-wrap text-neutral-300 shadow-inner">
                        {(formData as any).generated_output}
                    </div>
                </div>
            )}
            {/* Actions */}
            <div className="flex items-center justify-between pt-4 border-t border-neutral-900">
                <div className="text-sm">
                    {message && (
                        <span className={message.type === 'success' ? 'text-emerald-400' : 'text-red-400'}>
                            {message.text}
                        </span>
                    )}
                </div>
                <button
                    onClick={handleSave}
                    disabled={saving}
                    className="bg-white text-black px-6 py-2.5 rounded-lg font-medium hover:bg-neutral-200 active:scale-[0.98] transition-all disabled:opacity-70 disabled:cursor-not-allowed"
                >
                    {saving ? 'Saving...' : 'Save Changes'}
                </button>
            </div>
        </div >
    );
}
